### PR TITLE
SRE-1147 Create Session Manager Plugin Formula

### PR DESCRIPTION
**Pull request by whatisdot**
Closes https://snapsheettech.atlassian.net/browse/SRE-1147

This introduces a new formula for installing the `session-manager-plugin` for both Linux and macOS. This will be included as a dependency of the Tinker formula in a follow-up change.

# Testing

Checkout this branch:
```shell
git checkout jSRE_1147-update-homebrew-formula-depend
```

## Test with macOS

Make sure you don't have the Cask version installed.
```shell
brew remove session-manager-plugin
```

Install the commands.
```shell
brew install awscli jq
brew install --build-from-source Formula/session-manager-plugin.rb
```

Verify the brew test works.
```shell
brew test session-manager-plugin
```

Verify which version 
```shell
# for macOS it should be /usr/local/bin/session-manager-plugin
which session-manager-plugin

# should be 1.2.295.0
session-manager-plugin --version
```

Comment out this line in your .profile/.bashrc/.zshrc file.
Open a new CLI window
Renable the line in your .profile/.bashrc/.zshrc file.
```shell
PATH="${HOME}/Workspace/git-scripts:${PATH}"
```
Use this window to run the below commands so that your PATH doesn't include the version of `session-manager-plugin` bundled with git-scripts.

We can use the full path to the new version of awscli for testing: `/usr/local/bin/aws`

Start a new task and then connect with ECS Exec.
```shell
NEW_TASK=$(/usr/local/bin/aws ecs --profile user_session --region us-east-2 run-task \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --group authenticator \
  --enable-execute-command \
  --count 1 \
  --launch-type FARGATE \
  --task-definition awseb-fc51-deploy-testing-mrf8npvmdm-remote_session \
  --network-configuration 'awsvpcConfiguration={subnets=["subnet-09f2561f8b19ed301"]}')

echo $NEW_TASK | jq # to see what was created
```

Start a remote session using the installed plugin.
```shell
/usr/local/bin/aws ecs --profile user_session --region us-east-2 execute-command \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --task $(echo $NEW_TASK | jq -r '.tasks[0].taskArn') \
  --container remote_session \
  --interactive \
  --command /bin/bash
```

Run some commands to verify you're in an environment container:
```shell
The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-0e6e0af5ba1c7f022
root@ip-101-1-69-107:/app# rails c
Loading qa environment (Rails 5.2.5)
irb(main):001:0> User.count
D, [2022-03-18T20:17:57.410496 #336] DEBUG -- :    (1.4ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
D, [2022-03-18T20:17:57.416535 #336] DEBUG -- :    (1.3ms)  SELECT COUNT(*) FROM `users`
=> 144
irb(main):002:0> exit
root@ip-101-1-69-107:/app# exit
exit


Exiting session with sessionId: ecs-execute-command-0e6e0af5ba1c7f022.
```

Stop the task so it won't run forever.
```shell
/usr/local/bin/aws ecs --profile user_session --region us-east-2 stop-task \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --task $(echo $NEW_TASK | jq -r '.tasks[0].taskArn')
```

Remove the plugin so you can later verify it works as dependency.
```shell
brew remove session-manager-plugin
```

## Test with Linux
Open a new docker container for testing:
```shell
docker compose run --rm cli
```

Install the commands.
```shell
brew install awscli jq
brew install --build-from-source Formula/session-manager-plugin.rb
```

Verify the brew test works.
```shell
brew test session-manager-plugin
```

Verify which version 
```shell
# for Linux it should be /home/linuxbrew/.linuxbrew/bin/session-manager-plugin
which session-manager-plugin

# should be 1.2.295.0
session-manager-plugin --version
```

Start a new task and then connect with ECS Exec.
```shell
NEW_TASK=$(aws ecs --profile user_session --region us-east-2 run-task \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --group authenticator \
  --enable-execute-command \
  --count 1 \
  --launch-type FARGATE \
  --task-definition awseb-fc51-deploy-testing-mrf8npvmdm-remote_session \
  --network-configuration 'awsvpcConfiguration={subnets=["subnet-09f2561f8b19ed301"]}')

echo $NEW_TASK | jq # to see what was created
```

Start a remote session using the installed plugin.
```shell
aws ecs --profile user_session --region us-east-2 execute-command \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --task $(echo $NEW_TASK | jq -r '.tasks[0].taskArn') \
  --container remote_session \
  --interactive \
  --command /bin/bash
```

Run some commands to verify you're in an environment container:
```shell
The Session Manager plugin was installed successfully. Use the AWS CLI to start a session.


Starting session with SessionId: ecs-execute-command-0e6e0af5ba1c7f022
root@ip-101-1-69-107:/app# rails c
Loading qa environment (Rails 5.2.5)
irb(main):001:0> User.count
D, [2022-03-18T20:17:57.410496 #336] DEBUG -- :    (1.4ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
D, [2022-03-18T20:17:57.416535 #336] DEBUG -- :    (1.3ms)  SELECT COUNT(*) FROM `users`
=> 144
irb(main):002:0> exit
root@ip-101-1-69-107:/app# exit
exit


Exiting session with sessionId: ecs-execute-command-0e6e0af5ba1c7f022.
```

Stop the task so it won't run forever.
```shell
aws ecs --profile user_session --region us-east-2 stop-task \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --task $(echo $NEW_TASK | jq -r '.tasks[0].taskArn')
```

### CODE REVIEW

**Review by d10zero — CHANGES_REQUESTED** [review]
I see the following error when testing on MacOS:
```
 ↵ 1  brew install --build-from-source Formula/session-manager-plugin.rb
Error: Failed to load cask: Formula/session-manager-plugin.rb
Cask 'session-manager-plugin' is unreadable: wrong constant name #<Class:0x00007fa081d81868>
Warning: Treating Formula/session-manager-plugin.rb as a formula.
==> Downloading https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.295.0/mac/session-manager-plugin.pkg
######################################################################## 100.0%
==> tar xvf session-manager-plugin.pkg
==> tar xvf Payload
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/session-manager-plugin
Target /usr/local/bin/session-manager-plugin
already exists. You may want to remove it:
  rm '/usr/local/bin/session-manager-plugin'

To force the link and overwrite all conflicting files:
  brew link --overwrite session-manager-plugin

To list all files that would be deleted:
  brew link --overwrite --dry-run session-manager-plugin

Possible conflicting files are:
/usr/local/bin/session-manager-plugin -> /usr/local/sessionmanagerplugin/bin/session-manager-plugin
```

Also when trying to start a new task, I see the following error:
```
 ✔  NEW_TASK=$(/usr/local/bin/aws ecs --profile user_session --region us-east-2 run-task \
  --cluster awseb-fc51-deploy-testing-mrf8npvmdm \
  --group authenticator \
  --enable-execute-command \
  --count 1 \
  --launch-type FARGATE \
  --task-definition awseb-fc51-deploy-testing-mrf8npvmdm-remote_session \
  --network-configuration 'awsvpcConfiguration={subnets=["subnet-09f2561f8b19ed301"]}')
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --enable-execute-command
```

**Review by d10zero — APPROVED** [review]
CR: LG
FR: Confirmed session manager plugin is included and execute-command works as expected on both macos and linux.

**Review by deekom — DISMISSED** [review]
Changes look good, testing worked as expected.
May be we can add a simple test to run with `brew test` in next iteration.

**Comment by whatisdot** [comment]
Good catch, @deekom. I would have requested changes so that `brew test` works as expected. Currently it will break, and that's no good.

I'll push a change when I come back to this task.

**Review by deekom — APPROVED** [review]
Changes look good, `brew test` works as expected.

**Review by d10zero — APPROVED** [review]
I am pretty sure this is not an issue, but I just want to make note that I've seen the following error when downloading Tinker when testing on Linux
```
Error: Failed to load cask: Formula/session-manager-plugin.rb
Cask 'session-manager-plugin' is unreadable: wrong constant name #<Class:0x0000000003816e30>
Warning: Treating Formula/session-manager-plugin.rb as a formula.
==> Downloading https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.295.0/ubuntu_64bit/session-manager-plugin.deb
...
```

Even tho I see this error, the session-manager-plugin continues to download properly and all test steps following work as expected.

**Comment by whatisdot** [comment]
I've seen these errors when running other formula as well. The error only shows when running the `--build-from-source` option, and I haven't found any documentation yet on why this gets raised.

As @d10zero said, it doesn't prevent the installer from working. Merging to release and include as dependency in following release.

**Pull request merged**
