### PR TITLE
SRE-1201 Update Homebrew Formula for Release 0.3.1

### PR DESCRIPTION
**Pull request by deekom**
Closes https://snapsheettech.atlassian.net/browse/SRE-1201

Update tinker formula to install version 0.3.1

### Testing

Checkout this branch and remove existing installation:
```
git checkout jSRE_1201-update-homebrew-formula-for-re
brew remove tinker
```
Run the install:
```
brew install --build-from-source Formula/tinker.rb
brew test Formula/tinker.rb # Ensure test throws no error
```

Run sample Tinker commands to confirm that tinker works as expected:
```shell
tinker --version # Should return 0.3.1
LOG_LEVEL=trace tinker console
tinker tf imports --config infra/deploy-testing.yaml --json | jq
```
Remove this test version installed.

### CODE REVIEW

**Review by whatisdot — CHANGES_REQUESTED** [review]
This installed Tinker 0.3.0 when installing via homebrew in docker compose.

I've abridged areas below with the following:
```
# 
# ...etc...
# 
```
...otherwise it is unedited.

I confirmed that I am on the correct branch, and the `Formula/tinker.rb` file is referencing `0.3.1` as the version to install.

#### Output
```shell
dev.user@b0eac087da70:~/homebrew-core$ brew install --build-from-source Formula/tinker.rb
Error: Failed to load cask: Formula/tinker.rb
Cask 'tinker' is unreadable: wrong constant name #<Class:0x0000000003483160>
Warning: Treating Formula/tinker.rb as a formula.
==> Tapping snapsheet/core
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/snapsheet/homebrew-core'...
remote: Enumerating objects: 212, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 212 (delta 9), reused 6 (delta 5), pack-reused 190
Receiving objects: 100% (212/212), 46.14 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (76/76), done.
Tapped 2 formulae (21 files, 140.5KB).
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
######################################################################## 100.0%
#
# ...etc...
#
==> Downloading https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.295.0/ubuntu_64bit/session-manager-plugin.deb
######################################################################## 100.0%
==> Fetching tinker gem from GitHub packages.
Downloaded tinker-0.3.1
==> Installing dependencies for tinker: m4, ca-certificates, openssl@1.1, berkeley-db, gdbm, expat, perl, autoconf, automake, gmp, attr, coreutils, libgpg-error, libksba, libtool, libyaml, pkg-config, ncurses, readline, zlib, mpdecimal, sqlite, xz, bzip2, libffi, unzip, python@3.9, six, libpng, freetype, libxml2, gettext, util-linux, fontconfig, jbig2dec, jpeg, libidn, libtiff, little-cms2, openjpeg, isl, mpfr, libmpc, zstd, binutils, gcc, ghostscript, libpthread-stubs, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxfixes, libxi, libxrender, libxrandr, libxxf86vm, libxdamage, python@3.10, libedit, elfutils, llvm, gzip, libpciaccess, libdrm, wayland, libva, libvdpau, libxshmfence, libxv, libxvmc, lm-sensors, wayland-protocols, mesa, mesa-glu, libxinerama, xinput, freeglut, jasper, netpbm, psutils, uchardet, pcre, glib, groff, awscli and snapsheet/core/session-manager-plugin
==> Installing tinker dependency: m4
==> Pouring m4--1.4.19.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/m4/1.4.19: 39 files, 1.1MB
# 
# ...etc...
# 
==> Installing tinker dependency: awscli
==> Pouring awscli--2.6.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/awscli/2.6.0: 12,626 files, 111.1MB
==> Installing tinker dependency: snapsheet/core/session-manager-plugin
==> ar vx session-manager-plugin.deb
==> tar xvf control.tar.gz
==> tar xvf data.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/session-manager-plugin/1.2.295.0: 10 files, 10.4MB, built in 4 seconds
==> Installing tinker
==> Installing dedicated version of Ruby 2.7.1. This will take several minutes.
==> For detailed progress information, run the following in a new CLI:
==>   tail -f /home/dev.user/.cache/Homebrew/Logs/tinker/01.rvm
==> /home/linuxbrew/.linuxbrew/Cellar/tinker/0.3.1/.rvm/bin/rvm --autolibs=read-fail --with-gcc=gcc --verbose --debug install 2.7.1
==> Installing ruby gem for tinker 0.3.1.
==> For detailed progress information, run the following in a new CLI:
==>   tail -f /home/dev.user/.cache/Homebrew/Logs/tinker/02.gem
==> gem install /home/dev.user/.cache/Homebrew/tinker-0.3.1.gem
==> Creating Tinker bin entrypoints.
🍺  /home/linuxbrew/.linuxbrew/Cellar/tinker/0.3.1: 36,677 files, 504.9MB, built in 5 minutes 22 seconds
==> Running `brew cleanup tinker`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

==> Reinstalling 1 dependent with broken linkage from source:
snapsheet/core/tinker
==> Fetching tinker gem from GitHub packages.
Downloaded tinker-0.3.0
==> Reinstalling snapsheet/core/tinker
==> Installing dedicated version of Ruby 2.7.1. This will take several minutes.
==> For detailed progress information, run the following in a new CLI:
==>   tail -f /home/dev.user/.cache/Homebrew/Logs/tinker/01.rvm
==> /home/linuxbrew/.linuxbrew/Cellar/tinker/0.3.0/.rvm/bin/rvm --autolibs=read-fail --with-gcc=gcc --verbose --debug install 2.7.1
==> Installing ruby gem for tinker 0.3.0.
==> For detailed progress information, run the following in a new CLI:
==>   tail -f /home/dev.user/.cache/Homebrew/Logs/tinker/02.gem
==> gem install /home/dev.user/.cache/Homebrew/tinker-0.3.0.gem
==> Creating Tinker bin entrypoints.
🍺  /home/linuxbrew/.linuxbrew/Cellar/tinker/0.3.0: 36,655 files, 504.9MB, built in 5 minutes 11 seconds
dev.user@b0eac087da70:~/homebrew-core$
dev.user@b0eac087da70:~/homebrew-core$ tinker --version
0.3.0
```

**Review by whatisdot — APPROVED** [review]
The install works for macOS, which is are primary audience at the moment.

Approved, provided we create a separate story to identify the root cause of the issue and finding a way to address it on Linux.

**Comment by deekom** [comment]
Added a task to track the issue in Linux: https://snapsheettech.atlassian.net/browse/SRE-1209

**Review by d10zero — APPROVED** [review]
Confirmed works on macOS

**Pull request merged**
