### PR TITLE
Sail

### PR DESCRIPTION
**Pull request by raysn0w**
Adding sail v1.0.1 to the Snapsheet Tap

### CODE REVIEW

**Review by deekom — COMMENTED** [review]
Awesome work @raysn0w! I was able to install sail with following commands
```
git checkout sail
brew install --debug --build-from-source Formula/sail.rb
```
After installation, it seems to post message about `docker-compose.yml` which is missing.


Screen Shot 2022-03-16 at 10 01 54 AM

**Comment by deekom** [comment]
Couple of comments to get inline with the standard PR process
- Please add PR description and testing instructions (please refer to any of the [closed PRs](https://github.com/snapsheet/homebrew-core/pulls?q=is%3Apr+is%3Aclosed) for sample.)
- I have added a [release](https://github.com/snapsheet/homebrew-core/tree/1.0.3-rc) candidate branch. Please use that as base branch for this PR.

**Review by whatisdot — CHANGES_REQUESTED** [review]
Looking good, @raysn0w :) I have some change requests.

Can you move the `GitHubPrivateRepositoryDownloadStrategy` and `GitHubPrivateRepositoryReleaseDownloadStrategy` classes into files with a similar place and naming convention to what we did with the [RubyGemsDownloadStrategy](https://github.com/snapsheet/homebrew-core/blob/main/lib/ruby_gems_download_strategy.rb)? This is reusable for things other than Sail.
* `lib/git_hub_private_repository_download_strategy.rb`
* `lib/git_hub_private_repository_release_download_strategy.rb`

This isn't going to be maintained by the Homebrew team, so you should remove the license clause comments at the top of the class.

**Comment by raysn0w** [comment]
Hey @whatisdot / CC @Ben-Richards-SS ,

I was thinking about closing this PR given our previous discussion, since we consider sail to be in an alpha phase, we don't think that it would be good to merge into homebrew-core at this time.

We would like to move it into the homebrew-prerelease or homebrew-it repository/release-channel while we work on the app and once we reach a production-ready state we can submit a proper PR for homebrew-core.

Let me know if you have any comments or concerns.

**Comment by whatisdot** [comment]
@raysn0w @Ben-Richards-SS I did some searching and found [a solution for this in the Homebrew Formula Cookbook](https://docs.brew.sh/Formula-Cookbook#unstable-versions-head). If you specify `head (git remote)` you can enable someone to install the bleeding-edge version by saying `brew install sail --HEAD`. That will allow you to make constant pushes to the sail project, test with the `--HEAD` option, and (when you're ready) update the version number in the formula.

You can also follow a pattern I see where people create multiple formula files with a naming convention like this:
* `sail.rb` (for the latest)
* `sail@1.rb` (for specific version)
* `sail@2-rc.rb` (for release candidate)

That being said, trying to maintain the same executable with multiple formula, or especially from multiple Homebrew repositories, will lead to problems like "which one is running?" and "which one takes priority when installing?" These are problems that the Homebrew team and many contributors have already solved through mechanisms like the two I've mentioned above.

**Comment by Ben-Richards-SS** [comment]
@whatisdot we tested using the method you suggested. Unfortunately, because sail is a private repo it presents new issues. Given that I would say let's go with the solution we agreed upon yesterday and just create a new repo for the time being for development. I think that is the simplest solution and the quickest. If you could either grant me admin access to set up the repo and rules or create it for us that would be greatly appreciated!

**Comment by whatisdot** [comment]
@Ben-Richards-SS 
The Tinker project is private project, which is why we needed a separate download strategy to make that work. This Homebrew repository needs to be public, though. I could not find a mechanism within Homebrew to allow for private Homebrew repositories, so be aware of that.

**Pull request closed without merging**
